version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-deploy:
        docker:
            - image: circleci/node:10.19.0
        steps:
            - checkout
            - run:
                  name: Install Serverless
                  command: sudo npm i -g serverless npm@latest
            - run:
                  name: Install npm
                  command: npm install
            - run:
                  name: AWS credentials CircleCI profile
                  command: ./.circleci/install-credentials.sh
            - run:
                  name: Serverless deploy
                  command: sls deploy

workflows:
    build-and-deploy:
        jobs:
            - build-and-deploy:
                  context: serverlessProject
                  filters:
                      branches:
                          only:
                              - master